### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by slonofanya** [catberry/catberry-assets#1]
I executed command: "npm i catberry-assets".

Logs:

> jpegtran-bin@3.0.2 postinstall /var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Couldn't execute the `/var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --disable-shared --prefix="/var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor"
configure: error: no nasm (Netwide Assembler) found

```
at ChildProcess.exithandler (child_process.js:751:12)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

> gifsicle@3.0.1 postinstall /var/www/site/node_modules/catberry-assets/node_modules/csstime-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

**Comment by jughosta** [comment]
Do you have any problems with installation only `gulp-imagemin` package (it's used in catberry-assets)?
What is your OS?

**Comment by slonofanya** [comment]
OS: OS X 10.10.3.
Module "gulp-imagemin" have to be installed automatically, doesn't it?

**Comment by jughosta** [comment]
I mean, can you install `gulp-imagemin` package without errors? Maybe problem is not in `catberry-assets`, but in your environment

**Comment by slonofanya** [comment]
Yes, I installed "gulp-imagemin" separately and it works fine. 
But i think it need to be installed with "catberry-assets" via dependency.

**Comment by jughosta** [comment]
Yeah, `catberry-assets` has dependency `gulp-imagemin`. Now remove both packages from your project and execute again `npm install catberry-assets`

**Comment by slonofanya** [comment]
OK. I will test it next time. Thanks.
