### ISSUE TITLE
Watch mode fails after a syntax error in a LESS file

### ISSUE THREAD

**Issue by chetverikov** [catberry/catberry-assets#6]
If make a syntax error in a less file and save it, catberry-assets will output an error to the console. After that, the auto-rebuild feature does not work anymore. Only restart the application fixes the problem.

**Comment by rdner** [comment]
I did some research and apparently it's not a plugin issue, but an issue of the underlying library – CSS-Time, filed an issue there https://github.com/csstime/csstime-gulp-tasks/issues/23

**Comment by jughosta** [comment]
Fixed in https://github.com/catberry/catberry-assets/pull/10 and https://github.com/csstime/csstime-gulp-tasks/releases/tag/6.0.2
